"""Add event-driven accounting tables and denormalized fields

Revision ID: c36225a6afec
Revises: e2376adf5c74
Create Date: 2026-02-26 18:33:32.665933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36225a6afec'
down_revision: Union[str, None] = 'e2376adf5c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_CANCELLED', 'PAYMENT_RECEIVED', 'PAYMENT_REFUNDED', 'STUDENT_ENROLLED', 'STUDENT_WITHDRAWN', 'STUDENT_STATUS_CHANGED', 'MANUAL_ADJUSTMENT', 'BALANCE_CORRECTION', name='movementtype'), nullable=False),
    sa.Column('entity_type', sa.Enum('SCHOOL', 'STUDENT', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_movements_date', 'account_movements', ['created_at'], unique=False)
    op.create_index('ix_account_movements_entity', 'account_movements', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_account_movements_id'), 'account_movements', ['id'], unique=False)
    op.create_index('ix_account_movements_related', 'account_movements', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_index('ix_account_movements_type', 'account_movements', ['movement_type', 'created_at'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('SCHOOL', 'STUDENT', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='snapshottype'), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('active_students', sa.Integer(), nullable=True),
    sa.Column('inactive_students', sa.Integer(), nullable=True),
    sa.Column('total_invoiced', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pending', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=True),
    sa.Column('paid_invoices', sa.Integer(), nullable=True),
    sa.Column('pending_invoices', sa.Integer(), nullable=True),
    sa.Column('overdue_invoices', sa.Integer(), nullable=True),
    sa.Column('total_payments', sa.Integer(), nullable=True),
    sa.Column('payments_this_period', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'snapshot_date', 'snapshot_type', name='uq_snapshot_entity_date_type')
    )
    op.create_index(op.f('ix_account_snapshots_id'), 'account_snapshots', ['id'], unique=False)
    op.create_index('ix_snapshots_date', 'account_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_snapshots_entity_date', 'account_snapshots', ['entity_type', 'entity_id', 'snapshot_date'], unique=False)
    op.create_index('ix_snapshots_type_date', 'account_snapshots', ['snapshot_type', 'snapshot_date'], unique=False)
    op.add_column('schools', sa.Column('total_students', sa.Integer(), server_default='0', nullable=False))
    op.add_column('schools', sa.Column('active_students', sa.Integer(), server_default='0', nullable=False))
    op.add_column('schools', sa.Column('total_invoiced', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('schools', sa.Column('total_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('schools', sa.Column('total_pending', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('schools', sa.Column('cache_updated_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('total_invoiced', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('students', sa.Column('total_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('students', sa.Column('total_pending', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('students', sa.Column('cache_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'cache_updated_at')
    op.drop_column('students', 'total_pending')
    op.drop_column('students', 'total_paid')
    op.drop_column('students', 'total_invoiced')
    op.drop_column('schools', 'cache_updated_at')
    op.drop_column('schools', 'total_pending')
    op.drop_column('schools', 'total_paid')
    op.drop_column('schools', 'total_invoiced')
    op.drop_column('schools', 'active_students')
    op.drop_column('schools', 'total_students')
    op.drop_index('ix_snapshots_type_date', table_name='account_snapshots')
    op.drop_index('ix_snapshots_entity_date', table_name='account_snapshots')
    op.drop_index('ix_snapshots_date', table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index('ix_account_movements_type', table_name='account_movements')
    op.drop_index('ix_account_movements_related', table_name='account_movements')
    op.drop_index(op.f('ix_account_movements_id'), table_name='account_movements')
    op.drop_index('ix_account_movements_entity', table_name='account_movements')
    op.drop_index('ix_account_movements_date', table_name='account_movements')
    op.drop_table('account_movements')
    # ### end Alembic commands ###
